name: Build and Deploy OMLS Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Build frontend (React)
      - name: Install and build frontend
        working-directory: ./Omls.Functions
        run: |
          npm install
          npm run build
        env:
          REACT_APP_AZURE_MYSQL_DATABASE: ${{ secrets.REACT_APP_AZURE_MYSQL_DATABASE }}
          REACT_APP_AZURE_MYSQL_HOST: ${{ secrets.REACT_APP_AZURE_MYSQL_HOST }}
          REACT_APP_AZURE_MYSQL_PASSWORD: ${{ secrets.REACT_APP_AZURE_MYSQL_PASSWORD }}
          REACT_APP_AZURE_MYSQL_PORT: ${{ secrets.REACT_APP_AZURE_MYSQL_PORT }}
          REACT_APP_AZURE_MYSQL_SSL: ${{ secrets.REACT_APP_AZURE_MYSQL_SSL }}
          REACT_APP_AZURE_MYSQL_USER: ${{ secrets.REACT_APP_AZURE_MYSQL_USER }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

      - name: Zip backend for deployment
        run: zip -r backend.zip build
        working-directory: ./Omls.Functions

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: ./Omls.Functions/backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend

      - name: Unzip backend
        run: unzip backend.zip -d frontend

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omls-website'
          slot-name: 'Production'
          package: ./backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4A8D1DECEA2F479C973B5C446E433B04 }}
