name: Build and deploy Node.js app to Azure Web App - omls-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: Omls.Client/src/frontend
        
        env:
          REACT_APP_AZURE_MYSQL_DATABASE: ${{ secrets.REACT_APP_AZURE_MYSQL_DATABASE }}
          REACT_APP_AZURE_MYSQL_HOST: ${{ secrets.REACT_APP_AZURE_MYSQL_HOST }}
          REACT_APP_AZURE_MYSQL_PASSWORD: ${{ secrets.REACT_APP_AZURE_MYSQL_PASSWORD }}
          REACT_APP_AZURE_MYSQL_PORT: ${{ secrets.REACT_APP_AZURE_MYSQL_PORT }}
          REACT_APP_AZURE_MYSQL_SSL: ${{ secrets.REACT_APP_AZURE_MYSQL_SSL }}
          REACT_APP_AZURE_MYSQL_USER: ${{ secrets.REACT_APP_AZURE_MYSQL_USER }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

      - name: Zip artifact for deployment
        run: zip -r release.zip .
        working-directory: Omls.Client

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: Omls.Client/src/frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omls-website'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4A8D1DECEA2F479C973B5C446E433B04 }}
