name: Azure Web App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      PROJECT_DIR: Orcimed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Create .env file
        run: |
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" >> $PROJECT_DIR/.env
          echo "AZURE_MYSQL_DATABASE=${{ secrets.AZURE_MYSQL_DATABASE }}" >> $PROJECT_DIR/.env
          echo "AZURE_MYSQL_HOST=${{ secrets.AZURE_MYSQL_HOST }}" >> $PROJECT_DIR/.env
          echo "AZURE_MYSQL_PASSWORD=${{ secrets.AZURE_MYSQL_PASSWORD }}" >> $PROJECT_DIR/.env
          echo "AZURE_MYSQL_PORT=${{ secrets.AZURE_MYSQL_PORT }}" >> $PROJECT_DIR/.env
          echo "AZURE_MYSQL_SSL=${{ secrets.AZURE_MYSQL_SSL }}" >> $PROJECT_DIR/.env
          echo "AZURE_MYSQL_USER=${{ secrets.AZURE_MYSQL_USER }}" >> $PROJECT_DIR/.env

      - name: Install dependencies and build
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        working-directory: ${{ env.PROJECT_DIR }}
        run: zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.PROJECT_DIR }}/release.zip

  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omls-website' # Update with your App Service name
          slot-name: 'Production'  # Optional
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_924283B181FD4275AABED26CE5856552 }}
